// Local OpenCode plugin entrypoint.
//
// OpenCode discovers a plugin directory by its `index.ts` entry. This package's
// real entrypoint is `dist/plugin.js`, which normalizes both host APIs from a
// single default export:
//   - V2 hosts use `id` + `setup` (native V2 plugin API)
//   - V1 hosts use `server`    (legacy hook-map plugin API)
//
// `dist/` is generated by `tsc` (plus the web UI build) and is not committed.
// Run the build before using this directory as a plugin source.
export { default } from "./dist/plugin.js"
